platform :ios, '10.0'
workspace 'Runner.xcworkspace'


pod 'GoogleMaps'


target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

end
