platform :ios, '11.0'
$FirebaseSDKVersion = '9.9.0'
pod 'GoogleMaps'
pod 'Firebase/Firestore'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

end
